#!/bin/bash
#inštalácia FastQC a MultiQC, ak ešte nie sú
sudo apt install fastqc
sudo apt install multiqc

#nastavenie premennej s názvom súboru
datafile="SHbasic_1fastq.gz"

#vytvorenie nového directory pre QC výsledky
mkdir QC_results

#spustenie FastQC súboru a uloženie výsledkov do vytvoreného directory
fastqc $datafile -o QC_results/

#využitie fastQC pre viac súborov naraz pomocou funkcie for loop
for file in *.fastq.gz
do
    fastqc $file -o QC_results/
done

#sumarizácia výsledkov pomocou MultiQC
multiqc QC_results/ -o QC_results/summary/
